/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generic_system_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {4, 4, 1};
static const casadi_int casadi_s2[3] = {4, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {28, 1, 1};

/* generic_system_model_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[28])->(o0[4],o1[4x4],o2[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[4]? arg[4][0] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=arg[4]? arg[4][4] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=(a03*a04);
  a02=(a02+a05);
  a05=arg[4]? arg[4][8] : 0;
  a06=arg[0]? arg[0][2] : 0;
  a07=(a05*a06);
  a02=(a02+a07);
  a07=arg[4]? arg[4][12] : 0;
  a08=arg[0]? arg[0][3] : 0;
  a09=(a07*a08);
  a02=(a02+a09);
  a09=arg[4]? arg[4][16] : 0;
  a10=arg[3]? arg[3][0] : 0;
  a11=(a09*a10);
  a12=arg[4]? arg[4][20] : 0;
  a13=arg[3]? arg[3][1] : 0;
  a14=(a12*a13);
  a11=(a11+a14);
  a02=(a02+a11);
  a11=arg[4]? arg[4][24] : 0;
  a02=(a02+a11);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[4]? arg[4][1] : 0;
  a11=(a02*a01);
  a14=arg[4]? arg[4][5] : 0;
  a15=(a14*a04);
  a11=(a11+a15);
  a15=arg[4]? arg[4][9] : 0;
  a16=(a15*a06);
  a11=(a11+a16);
  a16=arg[4]? arg[4][13] : 0;
  a17=(a16*a08);
  a11=(a11+a17);
  a17=arg[4]? arg[4][17] : 0;
  a18=(a17*a10);
  a19=arg[4]? arg[4][21] : 0;
  a20=(a19*a13);
  a18=(a18+a20);
  a11=(a11+a18);
  a18=arg[4]? arg[4][25] : 0;
  a11=(a11+a18);
  if (res[0]!=0) res[0][1]=a11;
  a11=arg[4]? arg[4][2] : 0;
  a18=(a11*a01);
  a20=arg[4]? arg[4][6] : 0;
  a21=(a20*a04);
  a18=(a18+a21);
  a21=arg[4]? arg[4][10] : 0;
  a22=(a21*a06);
  a18=(a18+a22);
  a22=arg[4]? arg[4][14] : 0;
  a23=(a22*a08);
  a18=(a18+a23);
  a23=arg[4]? arg[4][18] : 0;
  a24=(a23*a10);
  a25=arg[4]? arg[4][22] : 0;
  a26=(a25*a13);
  a24=(a24+a26);
  a18=(a18+a24);
  a24=arg[4]? arg[4][26] : 0;
  a18=(a18+a24);
  if (res[0]!=0) res[0][2]=a18;
  a18=arg[4]? arg[4][3] : 0;
  a01=(a18*a01);
  a24=arg[4]? arg[4][7] : 0;
  a04=(a24*a04);
  a01=(a01+a04);
  a04=arg[4]? arg[4][11] : 0;
  a06=(a04*a06);
  a01=(a01+a06);
  a06=arg[4]? arg[4][15] : 0;
  a08=(a06*a08);
  a01=(a01+a08);
  a08=arg[4]? arg[4][19] : 0;
  a10=(a08*a10);
  a26=arg[4]? arg[4][23] : 0;
  a13=(a26*a13);
  a10=(a10+a13);
  a01=(a01+a10);
  a10=arg[4]? arg[4][27] : 0;
  a01=(a01+a10);
  if (res[0]!=0) res[0][3]=a01;
  a01=arg[1]? arg[1][0] : 0;
  a10=(a00*a01);
  a13=arg[1]? arg[1][1] : 0;
  a27=(a03*a13);
  a10=(a10+a27);
  a27=arg[1]? arg[1][2] : 0;
  a28=(a05*a27);
  a10=(a10+a28);
  a28=arg[1]? arg[1][3] : 0;
  a29=(a07*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][0]=a10;
  a10=(a02*a01);
  a29=(a14*a13);
  a10=(a10+a29);
  a29=(a15*a27);
  a10=(a10+a29);
  a29=(a16*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][1]=a10;
  a10=(a11*a01);
  a29=(a20*a13);
  a10=(a10+a29);
  a29=(a21*a27);
  a10=(a10+a29);
  a29=(a22*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][2]=a10;
  a01=(a18*a01);
  a13=(a24*a13);
  a01=(a01+a13);
  a27=(a04*a27);
  a01=(a01+a27);
  a28=(a06*a28);
  a01=(a01+a28);
  if (res[1]!=0) res[1][3]=a01;
  a01=arg[1]? arg[1][4] : 0;
  a28=(a00*a01);
  a27=arg[1]? arg[1][5] : 0;
  a13=(a03*a27);
  a28=(a28+a13);
  a13=arg[1]? arg[1][6] : 0;
  a10=(a05*a13);
  a28=(a28+a10);
  a10=arg[1]? arg[1][7] : 0;
  a29=(a07*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][4]=a28;
  a28=(a02*a01);
  a29=(a14*a27);
  a28=(a28+a29);
  a29=(a15*a13);
  a28=(a28+a29);
  a29=(a16*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][5]=a28;
  a28=(a11*a01);
  a29=(a20*a27);
  a28=(a28+a29);
  a29=(a21*a13);
  a28=(a28+a29);
  a29=(a22*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][6]=a28;
  a01=(a18*a01);
  a27=(a24*a27);
  a01=(a01+a27);
  a13=(a04*a13);
  a01=(a01+a13);
  a10=(a06*a10);
  a01=(a01+a10);
  if (res[1]!=0) res[1][7]=a01;
  a01=arg[1]? arg[1][8] : 0;
  a10=(a00*a01);
  a13=arg[1]? arg[1][9] : 0;
  a27=(a03*a13);
  a10=(a10+a27);
  a27=arg[1]? arg[1][10] : 0;
  a28=(a05*a27);
  a10=(a10+a28);
  a28=arg[1]? arg[1][11] : 0;
  a29=(a07*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][8]=a10;
  a10=(a02*a01);
  a29=(a14*a13);
  a10=(a10+a29);
  a29=(a15*a27);
  a10=(a10+a29);
  a29=(a16*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][9]=a10;
  a10=(a11*a01);
  a29=(a20*a13);
  a10=(a10+a29);
  a29=(a21*a27);
  a10=(a10+a29);
  a29=(a22*a28);
  a10=(a10+a29);
  if (res[1]!=0) res[1][10]=a10;
  a01=(a18*a01);
  a13=(a24*a13);
  a01=(a01+a13);
  a27=(a04*a27);
  a01=(a01+a27);
  a28=(a06*a28);
  a01=(a01+a28);
  if (res[1]!=0) res[1][11]=a01;
  a01=arg[1]? arg[1][12] : 0;
  a28=(a00*a01);
  a27=arg[1]? arg[1][13] : 0;
  a13=(a03*a27);
  a28=(a28+a13);
  a13=arg[1]? arg[1][14] : 0;
  a10=(a05*a13);
  a28=(a28+a10);
  a10=arg[1]? arg[1][15] : 0;
  a29=(a07*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][12]=a28;
  a28=(a02*a01);
  a29=(a14*a27);
  a28=(a28+a29);
  a29=(a15*a13);
  a28=(a28+a29);
  a29=(a16*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][13]=a28;
  a28=(a11*a01);
  a29=(a20*a27);
  a28=(a28+a29);
  a29=(a21*a13);
  a28=(a28+a29);
  a29=(a22*a10);
  a28=(a28+a29);
  if (res[1]!=0) res[1][14]=a28;
  a01=(a18*a01);
  a27=(a24*a27);
  a01=(a01+a27);
  a13=(a04*a13);
  a01=(a01+a13);
  a10=(a06*a10);
  a01=(a01+a10);
  if (res[1]!=0) res[1][15]=a01;
  a01=arg[2]? arg[2][0] : 0;
  a10=(a00*a01);
  a13=arg[2]? arg[2][1] : 0;
  a27=(a03*a13);
  a10=(a10+a27);
  a27=arg[2]? arg[2][2] : 0;
  a28=(a05*a27);
  a10=(a10+a28);
  a28=arg[2]? arg[2][3] : 0;
  a29=(a07*a28);
  a10=(a10+a29);
  a09=(a09+a10);
  if (res[2]!=0) res[2][0]=a09;
  a09=(a02*a01);
  a10=(a14*a13);
  a09=(a09+a10);
  a10=(a15*a27);
  a09=(a09+a10);
  a10=(a16*a28);
  a09=(a09+a10);
  a17=(a17+a09);
  if (res[2]!=0) res[2][1]=a17;
  a17=(a11*a01);
  a09=(a20*a13);
  a17=(a17+a09);
  a09=(a21*a27);
  a17=(a17+a09);
  a09=(a22*a28);
  a17=(a17+a09);
  a23=(a23+a17);
  if (res[2]!=0) res[2][2]=a23;
  a01=(a18*a01);
  a13=(a24*a13);
  a01=(a01+a13);
  a27=(a04*a27);
  a01=(a01+a27);
  a28=(a06*a28);
  a01=(a01+a28);
  a08=(a08+a01);
  if (res[2]!=0) res[2][3]=a08;
  a08=arg[2]? arg[2][4] : 0;
  a00=(a00*a08);
  a01=arg[2]? arg[2][5] : 0;
  a03=(a03*a01);
  a00=(a00+a03);
  a03=arg[2]? arg[2][6] : 0;
  a05=(a05*a03);
  a00=(a00+a05);
  a05=arg[2]? arg[2][7] : 0;
  a07=(a07*a05);
  a00=(a00+a07);
  a12=(a12+a00);
  if (res[2]!=0) res[2][4]=a12;
  a02=(a02*a08);
  a14=(a14*a01);
  a02=(a02+a14);
  a15=(a15*a03);
  a02=(a02+a15);
  a16=(a16*a05);
  a02=(a02+a16);
  a19=(a19+a02);
  if (res[2]!=0) res[2][5]=a19;
  a11=(a11*a08);
  a20=(a20*a01);
  a11=(a11+a20);
  a21=(a21*a03);
  a11=(a11+a21);
  a22=(a22*a05);
  a11=(a11+a22);
  a25=(a25+a11);
  if (res[2]!=0) res[2][6]=a25;
  a18=(a18*a08);
  a24=(a24*a01);
  a18=(a18+a24);
  a04=(a04*a03);
  a18=(a18+a04);
  a06=(a06*a05);
  a18=(a18+a06);
  a26=(a26+a18);
  if (res[2]!=0) res[2][7]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void generic_system_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int generic_system_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real generic_system_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* generic_system_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* generic_system_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int generic_system_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
